/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.testkiller.sobre;

import br.com.testkiller.beans.ConteudoTextArea;
import br.com.testkiller.internacionalizacao.Internacionalizacao;
import br.com.testkiller.view.TelaPrincipal;
import br.com.testkiller.view.q_04;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 805690
 */
public class Respostas extends javax.swing.JFrame {
    
     private Internacionalizacao internacionalizacao = new Internacionalizacao();
     private ConteudoTextArea conteudo = new ConteudoTextArea();
    
    public Respostas() {
        initComponents();
        jTable1.setModel(populaTabela());
        jTable1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_sobre = new javax.swing.JMenu();
        jMenuItem_sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Respostas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jMenu_sobre.setText("Menu");
        jMenu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_sobreActionPerformed(evt);
            }
        });

        jMenuItem_sobre.setText("Sair");
        jMenuItem_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_sobreActionPerformed(evt);
            }
        });
        jMenu_sobre.add(jMenuItem_sobre);

        jMenuBar1.add(jMenu_sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_sobreActionPerformed
        
    }//GEN-LAST:event_jMenu_sobreActionPerformed

    private void jMenuItem_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_sobreActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem_sobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

            //tela.setVisible(true);
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) 
        {
            //JOptionPane.showMessageDialog(null,info.getName() );
            if ("CDE/Motif".equals(info.getName()) ||"Metal".equals(info.getName()) ) {
                try {
                    UIManager.setLookAndFeel("de.muntjak.tinylookandfeel.TinyLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Respostas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Respostas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Respostas.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Respostas.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
        }
    
    
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Respostas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem_sobre;
    public static javax.swing.JMenu jMenu_sobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel populaTabela()
    {
       List<String> lista = new ArrayList<String>();
        
        int count = 1; 
        while(count <225)
        {
             try
                {
                      internacionalizacao.determinaPropriedadeTextArea1("qResp_"+count);
                      lista.add(internacionalizacao.getConteudoTextArea1());
   
                }
                catch(FileNotFoundException ex)
                {
                    Logger.getLogger(q_04.class.getName()).log(Level.SEVERE, null, ex);
                }
                catch (IOException ex)
                {
                    Logger.getLogger(q_04.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally
                {
                }
          count++;
        }
        
        
        
        
        
       DefaultTableModel model  = new DefaultTableModel(
            new Object [][] 
            {

                    {lista.get(0), lista.get(1), lista.get(2), lista.get(3),lista.get(4)},
                    {lista.get(5), lista.get(6), lista.get(7), lista.get(8),lista.get(9)},
                    {lista.get(10), lista.get(11), lista.get(12), lista.get(13),lista.get(14)},
                    {lista.get(15), lista.get(16), lista.get(17), lista.get(18),lista.get(19)},
                    {lista.get(20), lista.get(21), lista.get(22), lista.get(23),lista.get(24)},
                    {lista.get(25), lista.get(26), lista.get(27), lista.get(28),lista.get(29)},
                    {lista.get(30), lista.get(31), lista.get(32), lista.get(33),lista.get(34)},
                    {lista.get(35), lista.get(36), lista.get(37), lista.get(38),lista.get(39)},
                    {lista.get(40), lista.get(41), lista.get(42), lista.get(43),lista.get(44)},
                    {lista.get(45), lista.get(46), lista.get(47), lista.get(48),lista.get(49)},
                    {lista.get(50), lista.get(51), lista.get(52), lista.get(53),lista.get(54)},
                    {lista.get(55), lista.get(56), lista.get(57), lista.get(58),lista.get(59)},
                    {lista.get(60), lista.get(61), lista.get(62), lista.get(63),lista.get(64)},
                    {lista.get(65), lista.get(66), lista.get(67), lista.get(68),lista.get(69)},
                    {lista.get(70), lista.get(71), lista.get(72), lista.get(73),lista.get(74)},
                    {lista.get(75), lista.get(76), lista.get(77), lista.get(78),lista.get(79)},
                    {lista.get(80), lista.get(81), lista.get(82), lista.get(83),lista.get(84)},
                    {lista.get(85), lista.get(86), lista.get(87), lista.get(88),lista.get(89)},
                    {lista.get(90), lista.get(91), lista.get(92), lista.get(93),lista.get(94)},
                    {lista.get(95), lista.get(96), lista.get(97), lista.get(98),lista.get(99)},
                    {lista.get(100), lista.get(101), lista.get(102), lista.get(103),lista.get(104)},
                    {lista.get(105), lista.get(106), lista.get(107), lista.get(108),lista.get(109)},
                    {lista.get(110), lista.get(111), lista.get(112), lista.get(113),lista.get(114)},
                    {lista.get(115), lista.get(116), lista.get(117), lista.get(118),lista.get(119)},
                    {lista.get(120), lista.get(121), lista.get(122), lista.get(123),lista.get(124)},
                    {lista.get(125), lista.get(126), lista.get(127), lista.get(128),lista.get(129)},
                    {lista.get(130), lista.get(131), lista.get(132), lista.get(133),lista.get(134)},
                    {lista.get(135), lista.get(136), lista.get(137), lista.get(138),lista.get(139)},
                    {lista.get(140), lista.get(141), lista.get(142), lista.get(143),lista.get(144)},
                    {lista.get(145), lista.get(146), lista.get(147), lista.get(148),lista.get(149)},
                    {lista.get(150), lista.get(151), lista.get(152), lista.get(153),lista.get(154)},
                    {lista.get(155), lista.get(156), lista.get(157), lista.get(158),lista.get(159)},
                    {lista.get(160), lista.get(161), lista.get(162), lista.get(163),lista.get(164)},
                    {lista.get(165), lista.get(166), lista.get(167), lista.get(168),lista.get(169)},
                    {lista.get(170), lista.get(171), lista.get(172), lista.get(173),lista.get(174)},
                    {lista.get(175), lista.get(176), lista.get(177), lista.get(178),lista.get(179)},
                    {lista.get(180), lista.get(181), lista.get(182), lista.get(183),lista.get(184)},
                    {lista.get(185), lista.get(186), lista.get(187), lista.get(188),lista.get(189)},
                    {lista.get(190), lista.get(191), lista.get(192), lista.get(193),lista.get(194)},
                    {lista.get(195), lista.get(196), lista.get(197), lista.get(198),lista.get(199)},
                    {lista.get(200), lista.get(201), lista.get(202), lista.get(203),lista.get(204)},
                    {lista.get(205), lista.get(206), lista.get(207), lista.get(208),lista.get(209)},
                    {lista.get(210), lista.get(211), lista.get(212), lista.get(213),lista.get(214)},
                    {lista.get(215), lista.get(216), lista.get(217), lista.get(218),lista.get(219)},
                    {lista.get(220), lista.get(221), lista.get(222), lista.get(223),"-------------"},
            },
            
            new String [] {
                "", "", "", "",""
            }
        );
       
       return model;
       
       
    }
        
    

}
