/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaSobre.java
 *
 * Created on 06/06/2011, 15:37:13
 */
 
package br.com.testkiller.sobre;

import br.com.testkiller.view.TelaPrincipal;
import java.awt.Point;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author taraujo
 */
public class TelaSobre extends javax.swing.JFrame {

    /** Creates new form TelaSobre */
    
    
    Point pointDi = new Point( br.com.testkiller.util.RetonaSetaCalculosCartezianos.DimesionXY("largura"),
                               br.com.testkiller.util.RetonaSetaCalculosCartezianos.DimesionXY("altura"));

    public TelaSobre() {
        setResizable(false);

        setLocation(pointDi);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton_fecharSobre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre - tjca1@hotmail.com");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/testkiller/imgs/Thiago2.JPG"))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Versão do produto: Versão: 5.7.9 Final! \nJava: 1.6.0;\nEsse aplicativo e totalmente gratis !");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jTextArea2.setText("Nome: Thiago J. Correia de Araujo\nE-mail: tjca1@hotmail.com\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        jButton_fecharSobre.setText("Fechar");
        jButton_fecharSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fecharSobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_fecharSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_fecharSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_fecharSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fecharSobreActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_fecharSobreActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String[] args)
    {
    try
    {

        //tela.setVisible(true);
    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
    {
        //JOptionPane.showMessageDialog(null,info.getName() );
        if ("CDE/Motif".equals(info.getName()) ||"Metal".equals(info.getName()) ) {
            UIManager.setLookAndFeel("de.muntjak.tinylookandfeel.TinyLookAndFeel");
            TelaSobre tela  = new TelaSobre();
            tela.setVisible(true);
            break;
        }
    }
    } catch (UnsupportedLookAndFeelException e) {
      JOptionPane.showMessageDialog(null, "Problemas na Aparencia do Aplicativo - "+e);
    } catch (ClassNotFoundException e) {
     JOptionPane.showMessageDialog(null, "Problemas na Aparencia do Aplicativo - "+e);
    } catch (InstantiationException e) {
     JOptionPane.showMessageDialog(null, "Problemas na Aparencia do Aplicativo - "+e);
    } catch (IllegalAccessException e) {
      JOptionPane.showMessageDialog(null, "Problemas na Aparencia do Aplicativo - "+e);
    }



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_fecharSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

}
